name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
        python-version: [3.9, "3.10"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U -r requirements-dev.txt
      - name: Run pytest
        run: |
          python3 -m pytest
      - name: Flake8
        run: |
          flake8 pylexis

